version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
      args:
        NEXT_API_URL: ${NEXT_API_URL}
        NEXT_GS_URL: ${NEXT_GS_URL}
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    environment:
      TZ: Asia/Ulaanbaatar
      NODE_ENV: production
      NEXT_API_URL: ${NEXT_API_URL}
      NEXT_GS_URL: ${NEXT_GS_URL}
    restart: on-failure
    networks:
      - gov_network

networks:
  gov_network:
    name: gov_network
    external: true
